//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Cine.ProyectoS73.CatalogoServicesClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogoServicesClient.ICatalogoProyecto")]
    public interface ICatalogoProyecto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProyecto/GetData", ReplyAction="http://tempuri.org/ICatalogoProyecto/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProyecto/GetData", ReplyAction="http://tempuri.org/ICatalogoProyecto/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProyecto/Datos", ReplyAction="http://tempuri.org/ICatalogoProyecto/DatosResponse")]
        Servicios.CnS73.Catalogo[] Datos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProyecto/Datos", ReplyAction="http://tempuri.org/ICatalogoProyecto/DatosResponse")]
        System.Threading.Tasks.Task<Servicios.CnS73.Catalogo[]> DatosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoProyectoChannel : Web.Cine.ProyectoS73.CatalogoServicesClient.ICatalogoProyecto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoProyectoClient : System.ServiceModel.ClientBase<Web.Cine.ProyectoS73.CatalogoServicesClient.ICatalogoProyecto>, Web.Cine.ProyectoS73.CatalogoServicesClient.ICatalogoProyecto {
        
        public CatalogoProyectoClient() {
        }
        
        public CatalogoProyectoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoProyectoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoProyectoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoProyectoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public Servicios.CnS73.Catalogo[] Datos() {
            return base.Channel.Datos();
        }
        
        public System.Threading.Tasks.Task<Servicios.CnS73.Catalogo[]> DatosAsync() {
            return base.Channel.DatosAsync();
        }
    }
}
