//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnS73.Datos.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cn_S73Entities : DbContext
    {
        public Cn_S73Entities()
            : base("name=Cn_S73Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EM_CATALOGO> EM_CATALOGO { get; set; }
        public DbSet<EM_SALA> EM_SALA { get; set; }
        public DbSet<EM_TIPOPELICULA1> EM_TIPOPELICULA1 { get; set; }
    }
}
