//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnS73.Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_CATALOGO
    {
        public int IDPELICULA { get; set; }
        public string NOMBRE { get; set; }
        public string APODO { get; set; }
        public string CODIGOPILI { get; set; }
        public string ESTADO { get; set; }
        public string TIPOPELICULA { get; set; }
        public string URL { get; set; }
    }
}
