//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnS73.Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_TABLAVENTAS
    {
        public int IDVENTA { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public Nullable<int> NUMEROENTRADAS { get; set; }
        public Nullable<int> IDPELICULA { get; set; }
        public Nullable<int> ID_SALA { get; set; }
        public Nullable<decimal> TOTALPAGAR { get; set; }
        public Nullable<int> IDTIPOPELICULA { get; set; }
    
        public virtual EM_CATALOGO EM_CATALOGO { get; set; }
        public virtual EM_SALA EM_SALA { get; set; }
        public virtual EM_TIPOPELICULA1 EM_TIPOPELICULA1 { get; set; }
    }
}
